### ISSUE TITLE
some problem when install this lib

### ISSUE THREAD

**Issue by TimuJiang** [w3reality/es-pack-js#4]
es-pack-js@0.5.1 postinstall D:\lib\three-geo\node_modules\es-pack-js
> (cd ./node-polyfill && npm run install); (cd ./rustwasm-polyfill && npm i);

此时不应有 (cd。
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\es-pack-js\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! es-pack-js@0.5.1 postinstall: `(cd ./node-polyfill && npm run install); (cd ./rustwasm-polyfill && npm i);`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the es-pack-js@0.5.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\G007261\AppData\Roaming\npm-cache\_logs\2021-07-13T12_21_28_550Z-debug.log

**Comment by letsgo0** [comment]
I met the same problem. I run the code mentioned in README.md,
```
$ mkdir add
$ cd add
$ npm init
$ npm i -D es-pack-js  # ⬇️
```
and it shows the same error.
Did you solve it?
